messages:
  usage: "&eUsage: /gamemodecheck <MCID|*>"
  no-permission: "&cYou do not have permission to use this command."
  player-not-found: "&cPlayer {player} not found."
  player-mode: "&6Player {player}'s game mode: &a{mode}"
  list-header: "&6Game Modes:"
  mode-format: "&e{mode}: &a{players}"
